export const arr = [
  {
    Owner: "Akash",
    PropertyType: "Garage",
    Location: "Delhi",
    Price: "Rs 5000",
    id: 1,
  },
  {
    Owner: "Utkarsh",
    PropertyType: "Self-Storage",
    Location: "Bareilly",
    Price: "Rs 4000",
    id: 2,
  },
  {
    Owner: "Vijay",
    PropertyType: "Business Inventory",
    Location: "Kanpur",
    Price: "Rs 6000",
    id: 3,
  },
  {
    Owner: "Iqbal",
    PropertyType: "Climate-Control",
    Location: "Chandigarh",
    Price: "Rs 5000",
    id: 4,
  },
  {
    Owner: "Shiv",
    PropertyType: "Garage",
    Location: "Lucknow",
    price: "Rs 6000",
    id: 5,
  },
  {
    Owner: "Ankit",
    PropertyType: "Business Inventory",
    Location: "Mumbai",
    Price: "Rs 7000",
    id: 6,
  },
  {
    Owner: "Armaan",
    PropertyType: "Self-Storage",
    Location: "Chandigarh",
    price: "Rs 5000",
    id: 7,
  },
  {
    Owner: "Chitrang",
    PropertyType: "Climate-Control",
    Location: "Bareilly",
    Price: "Rs 6000",
    id: 8,
  },
  {
    Owner: "Prakhar",
    PropertyType: "Garage",
    Location: "Delhi",
    Price: "Rs 7000",
    id: 9,
  },
  {
    Owner: "Divyansh",
    PropertyType: "Self-storage",
    Location: "Mumbai",
    Price: "Rs 8000 ",
    id: 10,
  },
  {
    Owner: "Harshit",
    PropertyType: "Business Inventory",
    Location: "Lucknow",
    Price: "Rs 6000",
    id: 11,
  },
  {
    Owner: "Pranay",
    PropertyType: "Climate-Control",
    Location: "Chandigarh",
    Price: "Rs 8000",
    id: 12,
  },
  {
    Owner: "Jasmine",
    PropertyType: "Self-Storage",
    Location: "Delhi",
    Price: "Rs 9000",
    id: 13,
  },
  {
    Owner: "Ishita",
    PropertyType: "Business Inventory",
    Location: "Lucknow",
    Price: "Rs 8000",
    id: 14,
  },
  {
    Owner: "Tanisha",
    PropertyType: "Garage",
    Location: "Kanpur",
    Price: "Rs 5000",
    id: 15,
  },
  {
    Owner: "Anchal",
    PropertyType: "Climate-Control",
    Location: "Mumbai",
    Price: "Rs 9000",
    id: 16,
  },
];
